dic={
    'class':{
        'student':{
            'name':'mike',
            'marks':{
                'physics':70,
                'history':80
                }
            }
        }
    }
print(dic['class']['student']['marks']['history'])
